/** Icon set curated from lucide-vue-next (https://lucide.dev). */
import type { Component as VueComponent } from 'vue'
import {
  Accessibility,
  Activity,
  AirVent,
  Airplay,
  AlarmClock,
  Album,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Ambulance,
  Anchor,
  Antenna,
  Aperture,
  Apple,
  Archive,
  ArchiveRestore,
  ArchiveX,
  AreaChart,
  Armchair,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Asterisk,
  AtSign,
  Atom,
  Award,
  Axe,
  Baby,
  Badge,
  BadgeAlert,
  BadgeCent,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  BadgeInfo,
  BadgeMinus,
  BadgePlus,
  BadgeX,
  Ban,
  Banana,
  Banknote,
  BarChart2,
  BarChart3,
  Barcode,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  Beaker,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Bell,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  Bike,
  Binary,
  Bird,
  Blocks,
  Bluetooth,
  Bold,
  Bolt,
  Bone,
  Book,
  BookCheck,
  BookCopy,
  BookMarked,
  BookMinus,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookText,
  BookUser,
  BookX,
  Bookmark,
  BookmarkMinus,
  BookmarkPlus,
  BookmarkX,
  Bot,
  Box,
  Boxes,
  Brain,
  BrainCircuit,
  BrainCog,
  BrickWall,
  Briefcase,
  Brush,
  BrushCleaning,
  Bug,
  BugOff,
  BugPlay,
  Building,
  Building2,
  Bus,
  BusFront,
  Cake,
  CakeSlice,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  CalendarMinus,
  CalendarPlus,
  CalendarRange,
  CalendarSearch,
  CalendarX,
  Camera,
  Candy,
  CandyCane,
  Car,
  CarFront,
  CarTaxiFront,
  Carrot,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  Cast,
  Castle,
  Cat,
  Check,
  CheckCircle,
  ChefHat,
  Cherry,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Church,
  Cigarette,
  CigaretteOff,
  Circle,
  CircleCheck,
  CircleDollarSign,
  CircleDot,
  CircleMinus,
  CircleOff,
  CirclePlus,
  CircleX,
  CircuitBoard,
  Citrus,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardPaste,
  ClipboardX,
  Clock,
  Cloud,
  CloudDownload,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudOff,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudUpload,
  Club,
  Code,
  Coffee,
  Cog,
  Columns,
  Columns2,
  Columns3,
  Columns4,
  Combine,
  Compass,
  Component as ComponentIcon,
  Construction,
  Contact,
  Contact2,
  ContactRound,
  Container,
  Contrast,
  Cookie,
  CookingPot,
  Copy,
  Cpu,
  CreditCard,
  Crop,
  Cross,
  Crosshair,
  Crown,
  Database,
  Diamond,
  Disc,
  Disc2,
  Dna,
  Dog,
  DollarSign,
  DoorClosed,
  DoorOpen,
  Download,
  DownloadCloud,
  DraftingCompass,
  Droplet,
  Droplets,
  Ear,
  EarOff,
  Earth,
  Eclipse,
  Edit,
  Egg,
  EggFried,
  Eraser,
  EthernetPort,
  Euro,
  EvCharger,
  Expand,
  ExternalLink,
  Eye,
  EyeClosed,
  EyeOff,
  Factory,
  Fan,
  Fence,
  File,
  FileAudio,
  FileBox,
  FileCheck,
  FileCode,
  FileDown,
  FileImage,
  FileInput,
  FileJson,
  FileMinus,
  FileOutput,
  FilePen,
  FilePlus,
  FileQuestion,
  FileSearch,
  FileSignature,
  FileSliders,
  FileSpreadsheet,
  FileStack,
  FileSymlink,
  FileText,
  FileType,
  FileType2,
  FileUp,
  FileUser,
  FileVideo,
  FileVolume,
  FileWarning,
  FileX,
  Files,
  Film,
  Filter,
  Fingerprint,
  FireExtinguisher,
  Fish,
  FishOff,
  Flag,
  FlagOff,
  Flame,
  Flashlight,
  FlaskConical,
  FlipHorizontal,
  FlipVertical,
  Flower,
  Focus,
  Folder,
  FolderArchive,
  FolderCheck,
  FolderCog,
  FolderDot,
  FolderDown,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOutput,
  FolderPen,
  FolderPlus,
  FolderSearch,
  FolderSync,
  FolderTree,
  FolderUp,
  FolderX,
  Footprints,
  Forklift,
  Forward,
  Frown,
  Fuel,
  Fullscreen,
  GalleryHorizontal,
  GalleryThumbnails,
  GalleryVertical,
  Gamepad,
  Gamepad2,
  Gavel,
  Gem,
  Gift,
  GitBranch,
  GitCommit,
  GitFork,
  GitMerge,
  GitPullRequest,
  GlassWater,
  Glasses,
  Globe,
  Globe2,
  GlobeLock,
  GraduationCap,
  Grape,
  Grid3x3,
  GripVertical,
  Ham,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handshake,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  HardHat,
  Hash,
  Heading,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Heater,
  Helicopter,
  HelpCircle,
  Hexagon,
  Highlighter,
  History,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  House,
  HouseHeart,
  HousePlug,
  HousePlus,
  HouseWifi,
  IceCreamBowl,
  IceCreamCone,
  IdCard,
  Image,
  ImageDown,
  ImageMinus,
  ImageOff,
  ImagePlay,
  ImagePlus,
  ImageUp,
  Images,
  Inbox,
  Infinity,
  Info,
  Italic,
  Joystick,
  Kanban,
  Key,
  KeyRound,
  KeySquare,
  Keyboard,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Laugh,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  Leaf,
  Library,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  List,
  ListChecks,
  ListCollapse,
  ListEnd,
  ListFilter,
  ListMinus,
  ListOrdered,
  ListPlus,
  ListRestart,
  ListStart,
  ListTodo,
  ListTree,
  ListX,
  Loader2,
  Locate,
  LocateFixed,
  LocateOff,
  Lock,
  LockKeyhole,
  LockOpen,
  LogIn,
  LogOut,
  Lollipop,
  Magnet,
  Mail,
  MailCheck,
  MailMinus,
  MailOpen,
  MailPlus,
  MailQuestion,
  MailWarning,
  MailX,
  Map,
  MapPin,
  MapPinOff,
  MapPinned,
  Maximize,
  Maximize2,
  Medal,
  Megaphone,
  Meh,
  Menu,
  Merge,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Mic2,
  MicOff,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  Minimize,
  Minimize2,
  Minus,
  Monitor,
  MonitorPlay,
  MonitorSmartphone,
  MonitorSpeaker,
  Moon,
  MoonStar,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Mouse,
  MousePointer,
  MousePointer2,
  Move,
  Move3d,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  NavigationOff,
  Network,
  Newspaper,
  Nfc,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  NotepadText,
  Nut,
  Octagon,
  OctagonAlert,
  Orbit,
  Package,
  Package2,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  Paintbrush,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  PanelTop,
  Paperclip,
  ParkingMeter,
  Pause,
  PawPrint,
  PenLine,
  PenTool,
  Pencil,
  PencilLine,
  PencilRuler,
  Pentagon,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Pi,
  Pickaxe,
  PictureInPicture,
  PictureInPicture2,
  PieChart,
  PiggyBank,
  Pilcrow,
  Pill,
  PillBottle,
  Pin,
  PinOff,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  Plug,
  PlugZap,
  Plus,
  Popcorn,
  Power,
  Presentation,
  Printer,
  Projector,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radio,
  RadioTower,
  Rat,
  Ratio,
  Receipt,
  ReceiptCent,
  ReceiptText,
  Recycle,
  Redo,
  RefreshCcw,
  RefreshCw,
  RefreshCwOff,
  Refrigerator,
  RemoveFormatting,
  Reply,
  ReplyAll,
  Rocket,
  RockingChair,
  Rotate3d,
  RotateCcw,
  Route,
  RouteOff,
  Router,
  Rows,
  Rows2,
  Rows3,
  Rows4,
  Rss,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  Save,
  Scale,
  Scan,
  ScanBarcode,
  ScanEye,
  ScanFace,
  ScanHeart,
  ScanLine,
  ScanSearch,
  ScanText,
  School,
  Scissors,
  ScreenShare,
  ScreenShareOff,
  Scroll,
  ScrollText,
  Search,
  Send,
  SendHorizontal,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Settings,
  Shapes,
  Share,
  Share2,
  Sheet,
  Shell,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldHalf,
  ShieldQuestion,
  ShieldX,
  Ship,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrink,
  Sidebar,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  Signpost,
  SignpostBig,
  Siren,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  SortAsc,
  SortDesc,
  Soup,
  Spade,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  SpellCheck,
  Split,
  Sprout,
  Square,
  SquareArrowOutDownLeft,
  SquareArrowOutDownRight,
  SquareArrowOutUpLeft,
  SquareArrowOutUpRight,
  SquareCheck,
  SquareKanban,
  SquareMinus,
  SquarePen,
  SquarePlus,
  SquareX,
  Squirrel,
  Stamp,
  Star,
  Stars,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Swords,
  Syringe,
  Table,
  Table2,
  TableProperties,
  Tablet,
  TabletSmartphone,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  Text,
  TextCursor,
  TextSearch,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketMinus,
  TicketPercent,
  TicketPlus,
  TicketX,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Touchpad,
  TrafficCone,
  Train,
  TrainFront,
  TramFront,
  Trash,
  TreePine,
  Trees,
  Triangle,
  TriangleAlert,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Type,
  Umbrella,
  Underline,
  Undo,
  University,
  Unlink,
  Unlink2,
  Unlock,
  Upload,
  UploadCloud,
  Usb,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserRound,
  UserRoundCheck,
  UserRoundCog,
  UserRoundMinus,
  UserRoundPlus,
  UserRoundSearch,
  UserRoundX,
  UserSearch,
  UserX,
  Users,
  Users2,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Variable,
  Verified,
  Video,
  VideoOff,
  Voicemail,
  Volume2,
  VolumeX,
  Wallet,
  Wand2,
  Warehouse,
  WashingMachine,
  Watch,
  Waypoints,
  Webcam,
  Wheat,
  WholeWord,
  Wifi,
  Wind,
  Workflow,
  Worm,
  Wrench,
  X,
  XCircle,
  Zap,
  ZapOff,
} from 'lucide-vue-next'

export const iconography = [
  { name: 'accessibility', label: 'Accessibility', component: Accessibility },
  { name: 'activity', label: 'Activity', component: Activity },
  { name: 'air-vent', label: 'Air Vent', component: AirVent },
  { name: 'airplay', label: 'Airplay', component: Airplay },
  { name: 'alarm-clock', label: 'Alarm Clock', component: AlarmClock },
  { name: 'album', label: 'Album', component: Album },
  { name: 'alert-circle', label: 'Alert Circle', component: AlertCircle },
  { name: 'alert-triangle', label: 'Alert Triangle', component: AlertTriangle },
  { name: 'align-center', label: 'Align Center', component: AlignCenter },
  { name: 'align-left', label: 'Align Left', component: AlignLeft },
  { name: 'align-right', label: 'Align Right', component: AlignRight },
  { name: 'ambulance', label: 'Ambulance', component: Ambulance },
  { name: 'anchor', label: 'Anchor', component: Anchor },
  { name: 'antenna', label: 'Antenna', component: Antenna },
  { name: 'aperture', label: 'Aperture', component: Aperture },
  { name: 'apple', label: 'Apple', component: Apple },
  { name: 'archive', label: 'Archive', component: Archive },
  { name: 'archive-restore', label: 'Archive Restore', component: ArchiveRestore },
  { name: 'archive-x', label: 'Archive X', component: ArchiveX },
  { name: 'area-chart', label: 'Area Chart', component: AreaChart },
  { name: 'armchair', label: 'Armchair', component: Armchair },
  { name: 'arrow-down', label: 'Arrow Down', component: ArrowDown },
  { name: 'arrow-left', label: 'Arrow Left', component: ArrowLeft },
  { name: 'arrow-right', label: 'Arrow Right', component: ArrowRight },
  { name: 'arrow-up', label: 'Arrow Up', component: ArrowUp },
  { name: 'arrow-up-right', label: 'Arrow Up Right', component: ArrowUpRight },
  { name: 'asterisk', label: 'Asterisk', component: Asterisk },
  { name: 'at-sign', label: 'At Sign', component: AtSign },
  { name: 'atom', label: 'Atom', component: Atom },
  { name: 'award', label: 'Award', component: Award },
  { name: 'axe', label: 'Axe', component: Axe },
  { name: 'baby', label: 'Baby', component: Baby },
  { name: 'badge', label: 'Badge', component: Badge },
  { name: 'badge-alert', label: 'Badge Alert', component: BadgeAlert },
  { name: 'badge-cent', label: 'Badge Cent', component: BadgeCent },
  { name: 'badge-check', label: 'Badge Check', component: BadgeCheck },
  { name: 'badge-dollar-sign', label: 'Badge Dollar Sign', component: BadgeDollarSign },
  { name: 'badge-euro', label: 'Badge Euro', component: BadgeEuro },
  { name: 'badge-info', label: 'Badge Info', component: BadgeInfo },
  { name: 'badge-minus', label: 'Badge Minus', component: BadgeMinus },
  { name: 'badge-plus', label: 'Badge Plus', component: BadgePlus },
  { name: 'badge-x', label: 'Badge X', component: BadgeX },
  { name: 'ban', label: 'Ban', component: Ban },
  { name: 'banana', label: 'Banana', component: Banana },
  { name: 'banknote', label: 'Banknote', component: Banknote },
  { name: 'bar-chart-2', label: 'Bar Chart 2', component: BarChart2 },
  { name: 'bar-chart-3', label: 'Bar Chart 3', component: BarChart3 },
  { name: 'barcode', label: 'Barcode', component: Barcode },
  { name: 'bath', label: 'Bath', component: Bath },
  { name: 'battery', label: 'Battery', component: Battery },
  { name: 'battery-charging', label: 'Battery Charging', component: BatteryCharging },
  { name: 'battery-full', label: 'Battery Full', component: BatteryFull },
  { name: 'battery-low', label: 'Battery Low', component: BatteryLow },
  { name: 'beaker', label: 'Beaker', component: Beaker },
  { name: 'bed', label: 'Bed', component: Bed },
  { name: 'bed-double', label: 'Bed Double', component: BedDouble },
  { name: 'bed-single', label: 'Bed Single', component: BedSingle },
  { name: 'beef', label: 'Beef', component: Beef },
  { name: 'bell', label: 'Bell', component: Bell },
  { name: 'bell-minus', label: 'Bell Minus', component: BellMinus },
  { name: 'bell-off', label: 'Bell Off', component: BellOff },
  { name: 'bell-plus', label: 'Bell Plus', component: BellPlus },
  { name: 'bell-ring', label: 'Bell Ring', component: BellRing },
  { name: 'bike', label: 'Bike', component: Bike },
  { name: 'binary', label: 'Binary', component: Binary },
  { name: 'bird', label: 'Bird', component: Bird },
  { name: 'blocks', label: 'Blocks', component: Blocks },
  { name: 'bluetooth', label: 'Bluetooth', component: Bluetooth },
  { name: 'bold', label: 'Bold', component: Bold },
  { name: 'bolt', label: 'Bolt', component: Bolt },
  { name: 'bone', label: 'Bone', component: Bone },
  { name: 'book', label: 'Book', component: Book },
  { name: 'book-check', label: 'Book Check', component: BookCheck },
  { name: 'book-copy', label: 'Book Copy', component: BookCopy },
  { name: 'book-marked', label: 'Book Marked', component: BookMarked },
  { name: 'book-minus', label: 'Book Minus', component: BookMinus },
  { name: 'book-open', label: 'Book Open', component: BookOpen },
  { name: 'book-open-check', label: 'Book Open Check', component: BookOpenCheck },
  { name: 'book-open-text', label: 'Book Open Text', component: BookOpenText },
  { name: 'book-plus', label: 'Book Plus', component: BookPlus },
  { name: 'book-text', label: 'Book Text', component: BookText },
  { name: 'book-user', label: 'Book User', component: BookUser },
  { name: 'book-x', label: 'Book X', component: BookX },
  { name: 'bookmark', label: 'Bookmark', component: Bookmark },
  { name: 'bookmark-minus', label: 'Bookmark Minus', component: BookmarkMinus },
  { name: 'bookmark-plus', label: 'Bookmark Plus', component: BookmarkPlus },
  { name: 'bookmark-x', label: 'Bookmark X', component: BookmarkX },
  { name: 'bot', label: 'Bot', component: Bot },
  { name: 'box', label: 'Box', component: Box },
  { name: 'boxes', label: 'Boxes', component: Boxes },
  { name: 'brain', label: 'Brain', component: Brain },
  { name: 'brain-circuit', label: 'Brain Circuit', component: BrainCircuit },
  { name: 'brain-cog', label: 'Brain Cog', component: BrainCog },
  { name: 'brick-wall', label: 'Brick Wall', component: BrickWall },
  { name: 'briefcase', label: 'Briefcase', component: Briefcase },
  { name: 'brush', label: 'Brush', component: Brush },
  { name: 'brush-cleaning', label: 'Brush Cleaning', component: BrushCleaning },
  { name: 'bug', label: 'Bug', component: Bug },
  { name: 'bug-off', label: 'Bug Off', component: BugOff },
  { name: 'bug-play', label: 'Bug Play', component: BugPlay },
  { name: 'building', label: 'Building', component: Building },
  { name: 'building-2', label: 'Building 2', component: Building2 },
  { name: 'bus', label: 'Bus', component: Bus },
  { name: 'bus-front', label: 'Bus Front', component: BusFront },
  { name: 'cake', label: 'Cake', component: Cake },
  { name: 'cake-slice', label: 'Cake Slice', component: CakeSlice },
  { name: 'calendar', label: 'Calendar', component: Calendar },
  { name: 'calendar-check', label: 'Calendar Check', component: CalendarCheck },
  { name: 'calendar-clock', label: 'Calendar Clock', component: CalendarClock },
  { name: 'calendar-days', label: 'Calendar Days', component: CalendarDays },
  { name: 'calendar-heart', label: 'Calendar Heart', component: CalendarHeart },
  { name: 'calendar-minus', label: 'Calendar Minus', component: CalendarMinus },
  { name: 'calendar-plus', label: 'Calendar Plus', component: CalendarPlus },
  { name: 'calendar-range', label: 'Calendar Range', component: CalendarRange },
  { name: 'calendar-search', label: 'Calendar Search', component: CalendarSearch },
  { name: 'calendar-x', label: 'Calendar X', component: CalendarX },
  { name: 'camera', label: 'Camera', component: Camera },
  { name: 'candy', label: 'Candy', component: Candy },
  { name: 'candy-cane', label: 'Candy Cane', component: CandyCane },
  { name: 'car', label: 'Car', component: Car },
  { name: 'car-front', label: 'Car Front', component: CarFront },
  { name: 'car-taxi-front', label: 'Car Taxi Front', component: CarTaxiFront },
  { name: 'carrot', label: 'Carrot', component: Carrot },
  { name: 'case-lower', label: 'Case Lower', component: CaseLower },
  { name: 'case-sensitive', label: 'Case Sensitive', component: CaseSensitive },
  { name: 'case-upper', label: 'Case Upper', component: CaseUpper },
  { name: 'cast', label: 'Cast', component: Cast },
  { name: 'castle', label: 'Castle', component: Castle },
  { name: 'cat', label: 'Cat', component: Cat },
  { name: 'check', label: 'Check', component: Check },
  { name: 'check-circle', label: 'Check Circle', component: CheckCircle },
  { name: 'chef-hat', label: 'Chef Hat', component: ChefHat },
  { name: 'cherry', label: 'Cherry', component: Cherry },
  { name: 'chevron-down', label: 'Chevron Down', component: ChevronDown },
  { name: 'chevron-left', label: 'Chevron Left', component: ChevronLeft },
  { name: 'chevron-right', label: 'Chevron Right', component: ChevronRight },
  { name: 'chevron-up', label: 'Chevron Up', component: ChevronUp },
  { name: 'chevrons-left', label: 'Chevrons Left', component: ChevronsLeft },
  { name: 'chevrons-right', label: 'Chevrons Right', component: ChevronsRight },
  { name: 'church', label: 'Church', component: Church },
  { name: 'cigarette', label: 'Cigarette', component: Cigarette },
  { name: 'cigarette-off', label: 'Cigarette Off', component: CigaretteOff },
  { name: 'circle', label: 'Circle', component: Circle },
  { name: 'circle-check', label: 'Circle Check', component: CircleCheck },
  { name: 'circle-dollar-sign', label: 'Circle Dollar Sign', component: CircleDollarSign },
  { name: 'circle-dot', label: 'Circle Dot', component: CircleDot },
  { name: 'circle-minus', label: 'Circle Minus', component: CircleMinus },
  { name: 'circle-off', label: 'Circle Off', component: CircleOff },
  { name: 'circle-plus', label: 'Circle Plus', component: CirclePlus },
  { name: 'circle-x', label: 'Circle X', component: CircleX },
  { name: 'circuit-board', label: 'Circuit Board', component: CircuitBoard },
  { name: 'citrus', label: 'Citrus', component: Citrus },
  { name: 'clapperboard', label: 'Clapperboard', component: Clapperboard },
  { name: 'clipboard', label: 'Clipboard', component: Clipboard },
  { name: 'clipboard-check', label: 'Clipboard Check', component: ClipboardCheck },
  { name: 'clipboard-copy', label: 'Clipboard Copy', component: ClipboardCopy },
  { name: 'clipboard-list', label: 'Clipboard List', component: ClipboardList },
  { name: 'clipboard-paste', label: 'Clipboard Paste', component: ClipboardPaste },
  { name: 'clipboard-x', label: 'Clipboard X', component: ClipboardX },
  { name: 'clock', label: 'Clock', component: Clock },
  { name: 'cloud', label: 'Cloud', component: Cloud },
  { name: 'cloud-download', label: 'Cloud Download', component: CloudDownload },
  { name: 'cloud-drizzle', label: 'Cloud Drizzle', component: CloudDrizzle },
  { name: 'cloud-fog', label: 'Cloud Fog', component: CloudFog },
  { name: 'cloud-hail', label: 'Cloud Hail', component: CloudHail },
  { name: 'cloud-lightning', label: 'Cloud Lightning', component: CloudLightning },
  { name: 'cloud-moon', label: 'Cloud Moon', component: CloudMoon },
  { name: 'cloud-off', label: 'Cloud Off', component: CloudOff },
  { name: 'cloud-rain', label: 'Cloud Rain', component: CloudRain },
  { name: 'cloud-snow', label: 'Cloud Snow', component: CloudSnow },
  { name: 'cloud-sun', label: 'Cloud Sun', component: CloudSun },
  { name: 'cloud-upload', label: 'Cloud Upload', component: CloudUpload },
  { name: 'club', label: 'Club', component: Club },
  { name: 'code', label: 'Code', component: Code },
  { name: 'coffee', label: 'Coffee', component: Coffee },
  { name: 'cog', label: 'Cog', component: Cog },
  { name: 'columns', label: 'Columns', component: Columns },
  { name: 'columns-2', label: 'Columns 2', component: Columns2 },
  { name: 'columns-3', label: 'Columns 3', component: Columns3 },
  { name: 'columns-4', label: 'Columns 4', component: Columns4 },
  { name: 'combine', label: 'Combine', component: Combine },
  { name: 'compass', label: 'Compass', component: Compass },
  { name: 'component', label: 'Component', component: ComponentIcon },
  { name: 'construction', label: 'Construction', component: Construction },
  { name: 'contact', label: 'Contact', component: Contact },
  { name: 'contact-2', label: 'Contact 2', component: Contact2 },
  { name: 'contact-round', label: 'Contact Round', component: ContactRound },
  { name: 'container', label: 'Container', component: Container },
  { name: 'contrast', label: 'Contrast', component: Contrast },
  { name: 'cookie', label: 'Cookie', component: Cookie },
  { name: 'cooking-pot', label: 'Cooking Pot', component: CookingPot },
  { name: 'copy', label: 'Copy', component: Copy },
  { name: 'cpu', label: 'Cpu', component: Cpu },
  { name: 'credit-card', label: 'Credit Card', component: CreditCard },
  { name: 'crop', label: 'Crop', component: Crop },
  { name: 'cross', label: 'Cross', component: Cross },
  { name: 'crosshair', label: 'Crosshair', component: Crosshair },
  { name: 'crown', label: 'Crown', component: Crown },
  { name: 'database', label: 'Database', component: Database },
  { name: 'diamond', label: 'Diamond', component: Diamond },
  { name: 'disc', label: 'Disc', component: Disc },
  { name: 'disc-2', label: 'Disc 2', component: Disc2 },
  { name: 'dna', label: 'Dna', component: Dna },
  { name: 'dog', label: 'Dog', component: Dog },
  { name: 'dollar-sign', label: 'Dollar Sign', component: DollarSign },
  { name: 'door-closed', label: 'Door Closed', component: DoorClosed },
  { name: 'door-open', label: 'Door Open', component: DoorOpen },
  { name: 'download', label: 'Download', component: Download },
  { name: 'download-cloud', label: 'Download Cloud', component: DownloadCloud },
  { name: 'drafting-compass', label: 'Drafting Compass', component: DraftingCompass },
  { name: 'droplet', label: 'Droplet', component: Droplet },
  { name: 'droplets', label: 'Droplets', component: Droplets },
  { name: 'ear', label: 'Ear', component: Ear },
  { name: 'ear-off', label: 'Ear Off', component: EarOff },
  { name: 'earth', label: 'Earth', component: Earth },
  { name: 'eclipse', label: 'Eclipse', component: Eclipse },
  { name: 'edit', label: 'Edit', component: Edit },
  { name: 'egg', label: 'Egg', component: Egg },
  { name: 'egg-fried', label: 'Egg Fried', component: EggFried },
  { name: 'eraser', label: 'Eraser', component: Eraser },
  { name: 'ethernet-port', label: 'Ethernet Port', component: EthernetPort },
  { name: 'euro', label: 'Euro', component: Euro },
  { name: 'ev-charger', label: 'Ev Charger', component: EvCharger },
  { name: 'expand', label: 'Expand', component: Expand },
  { name: 'external-link', label: 'External Link', component: ExternalLink },
  { name: 'eye', label: 'Eye', component: Eye },
  { name: 'eye-closed', label: 'Eye Closed', component: EyeClosed },
  { name: 'eye-off', label: 'Eye Off', component: EyeOff },
  { name: 'factory', label: 'Factory', component: Factory },
  { name: 'fan', label: 'Fan', component: Fan },
  { name: 'fence', label: 'Fence', component: Fence },
  { name: 'file', label: 'File', component: File },
  { name: 'file-audio', label: 'File Audio', component: FileAudio },
  { name: 'file-box', label: 'File Box', component: FileBox },
  { name: 'file-check', label: 'File Check', component: FileCheck },
  { name: 'file-code', label: 'File Code', component: FileCode },
  { name: 'file-down', label: 'File Down', component: FileDown },
  { name: 'file-image', label: 'File Image', component: FileImage },
  { name: 'file-input', label: 'File Input', component: FileInput },
  { name: 'file-json', label: 'File Json', component: FileJson },
  { name: 'file-minus', label: 'File Minus', component: FileMinus },
  { name: 'file-output', label: 'File Output', component: FileOutput },
  { name: 'file-pen', label: 'File Pen', component: FilePen },
  { name: 'file-plus', label: 'File Plus', component: FilePlus },
  { name: 'file-question', label: 'File Question', component: FileQuestion },
  { name: 'file-search', label: 'File Search', component: FileSearch },
  { name: 'file-signature', label: 'File Signature', component: FileSignature },
  { name: 'file-sliders', label: 'File Sliders', component: FileSliders },
  { name: 'file-spreadsheet', label: 'File Spreadsheet', component: FileSpreadsheet },
  { name: 'file-stack', label: 'File Stack', component: FileStack },
  { name: 'file-symlink', label: 'File Symlink', component: FileSymlink },
  { name: 'file-text', label: 'File Text', component: FileText },
  { name: 'file-type', label: 'File Type', component: FileType },
  { name: 'file-type-2', label: 'File Type 2', component: FileType2 },
  { name: 'file-up', label: 'File Up', component: FileUp },
  { name: 'file-user', label: 'File User', component: FileUser },
  { name: 'file-video', label: 'File Video', component: FileVideo },
  { name: 'file-volume', label: 'File Volume', component: FileVolume },
  { name: 'file-warning', label: 'File Warning', component: FileWarning },
  { name: 'file-x', label: 'File X', component: FileX },
  { name: 'files', label: 'Files', component: Files },
  { name: 'film', label: 'Film', component: Film },
  { name: 'filter', label: 'Filter', component: Filter },
  { name: 'fingerprint', label: 'Fingerprint', component: Fingerprint },
  { name: 'fire-extinguisher', label: 'Fire Extinguisher', component: FireExtinguisher },
  { name: 'fish', label: 'Fish', component: Fish },
  { name: 'fish-off', label: 'Fish Off', component: FishOff },
  { name: 'flag', label: 'Flag', component: Flag },
  { name: 'flag-off', label: 'Flag Off', component: FlagOff },
  { name: 'flame', label: 'Flame', component: Flame },
  { name: 'flashlight', label: 'Flashlight', component: Flashlight },
  { name: 'flask-conical', label: 'Flask Conical', component: FlaskConical },
  { name: 'flip-horizontal', label: 'Flip Horizontal', component: FlipHorizontal },
  { name: 'flip-vertical', label: 'Flip Vertical', component: FlipVertical },
  { name: 'flower', label: 'Flower', component: Flower },
  { name: 'focus', label: 'Focus', component: Focus },
  { name: 'folder', label: 'Folder', component: Folder },
  { name: 'folder-archive', label: 'Folder Archive', component: FolderArchive },
  { name: 'folder-check', label: 'Folder Check', component: FolderCheck },
  { name: 'folder-cog', label: 'Folder Cog', component: FolderCog },
  { name: 'folder-dot', label: 'Folder Dot', component: FolderDot },
  { name: 'folder-down', label: 'Folder Down', component: FolderDown },
  { name: 'folder-git', label: 'Folder Git', component: FolderGit },
  { name: 'folder-git-2', label: 'Folder Git 2', component: FolderGit2 },
  { name: 'folder-heart', label: 'Folder Heart', component: FolderHeart },
  { name: 'folder-input', label: 'Folder Input', component: FolderInput },
  { name: 'folder-kanban', label: 'Folder Kanban', component: FolderKanban },
  { name: 'folder-key', label: 'Folder Key', component: FolderKey },
  { name: 'folder-lock', label: 'Folder Lock', component: FolderLock },
  { name: 'folder-minus', label: 'Folder Minus', component: FolderMinus },
  { name: 'folder-open', label: 'Folder Open', component: FolderOpen },
  { name: 'folder-output', label: 'Folder Output', component: FolderOutput },
  { name: 'folder-pen', label: 'Folder Pen', component: FolderPen },
  { name: 'folder-plus', label: 'Folder Plus', component: FolderPlus },
  { name: 'folder-search', label: 'Folder Search', component: FolderSearch },
  { name: 'folder-sync', label: 'Folder Sync', component: FolderSync },
  { name: 'folder-tree', label: 'Folder Tree', component: FolderTree },
  { name: 'folder-up', label: 'Folder Up', component: FolderUp },
  { name: 'folder-x', label: 'Folder X', component: FolderX },
  { name: 'footprints', label: 'Footprints', component: Footprints },
  { name: 'forklift', label: 'Forklift', component: Forklift },
  { name: 'forward', label: 'Forward', component: Forward },
  { name: 'frown', label: 'Frown', component: Frown },
  { name: 'fuel', label: 'Fuel', component: Fuel },
  { name: 'fullscreen', label: 'Fullscreen', component: Fullscreen },
  { name: 'gallery-horizontal', label: 'Gallery Horizontal', component: GalleryHorizontal },
  { name: 'gallery-thumbnails', label: 'Gallery Thumbnails', component: GalleryThumbnails },
  { name: 'gallery-vertical', label: 'Gallery Vertical', component: GalleryVertical },
  { name: 'gamepad', label: 'Gamepad', component: Gamepad },
  { name: 'gamepad-2', label: 'Gamepad 2', component: Gamepad2 },
  { name: 'gavel', label: 'Gavel', component: Gavel },
  { name: 'gem', label: 'Gem', component: Gem },
  { name: 'gift', label: 'Gift', component: Gift },
  { name: 'git-branch', label: 'Git Branch', component: GitBranch },
  { name: 'git-commit', label: 'Git Commit', component: GitCommit },
  { name: 'git-fork', label: 'Git Fork', component: GitFork },
  { name: 'git-merge', label: 'Git Merge', component: GitMerge },
  { name: 'git-pull-request', label: 'Git Pull Request', component: GitPullRequest },
  { name: 'glass-water', label: 'Glass Water', component: GlassWater },
  { name: 'glasses', label: 'Glasses', component: Glasses },
  { name: 'globe', label: 'Globe', component: Globe },
  { name: 'globe-2', label: 'Globe 2', component: Globe2 },
  { name: 'globe-lock', label: 'Globe Lock', component: GlobeLock },
  { name: 'graduation-cap', label: 'Graduation Cap', component: GraduationCap },
  { name: 'grape', label: 'Grape', component: Grape },
  { name: 'grid-3x3', label: 'Grid 3x3', component: Grid3x3 },
  { name: 'grip-vertical', label: 'Grip Vertical', component: GripVertical },
  { name: 'ham', label: 'Ham', component: Ham },
  { name: 'hammer', label: 'Hammer', component: Hammer },
  { name: 'hand', label: 'Hand', component: Hand },
  { name: 'hand-coins', label: 'Hand Coins', component: HandCoins },
  { name: 'hand-heart', label: 'Hand Heart', component: HandHeart },
  { name: 'hand-helping', label: 'Hand Helping', component: HandHelping },
  { name: 'hand-metal', label: 'Hand Metal', component: HandMetal },
  { name: 'hand-platter', label: 'Hand Platter', component: HandPlatter },
  { name: 'handshake', label: 'Handshake', component: Handshake },
  { name: 'hard-drive', label: 'Hard Drive', component: HardDrive },
  { name: 'hard-drive-download', label: 'Hard Drive Download', component: HardDriveDownload },
  { name: 'hard-drive-upload', label: 'Hard Drive Upload', component: HardDriveUpload },
  { name: 'hard-hat', label: 'Hard Hat', component: HardHat },
  { name: 'hash', label: 'Hash', component: Hash },
  { name: 'heading', label: 'Heading', component: Heading },
  { name: 'headphones', label: 'Headphones', component: Headphones },
  { name: 'heart', label: 'Heart', component: Heart },
  { name: 'heart-handshake', label: 'Heart Handshake', component: HeartHandshake },
  { name: 'heart-pulse', label: 'Heart Pulse', component: HeartPulse },
  { name: 'heater', label: 'Heater', component: Heater },
  { name: 'helicopter', label: 'Helicopter', component: Helicopter },
  { name: 'help-circle', label: 'Help Circle', component: HelpCircle },
  { name: 'hexagon', label: 'Hexagon', component: Hexagon },
  { name: 'highlighter', label: 'Highlighter', component: Highlighter },
  { name: 'history', label: 'History', component: History },
  { name: 'home', label: 'Home', component: Home },
  { name: 'hospital', label: 'Hospital', component: Hospital },
  { name: 'hotel', label: 'Hotel', component: Hotel },
  { name: 'hourglass', label: 'Hourglass', component: Hourglass },
  { name: 'house', label: 'House', component: House },
  { name: 'house-heart', label: 'House Heart', component: HouseHeart },
  { name: 'house-plug', label: 'House Plug', component: HousePlug },
  { name: 'house-plus', label: 'House Plus', component: HousePlus },
  { name: 'house-wifi', label: 'House Wifi', component: HouseWifi },
  { name: 'ice-cream-bowl', label: 'Ice Cream Bowl', component: IceCreamBowl },
  { name: 'ice-cream-cone', label: 'Ice Cream Cone', component: IceCreamCone },
  { name: 'id-card', label: 'Id Card', component: IdCard },
  { name: 'image', label: 'Image', component: Image },
  { name: 'image-down', label: 'Image Down', component: ImageDown },
  { name: 'image-minus', label: 'Image Minus', component: ImageMinus },
  { name: 'image-off', label: 'Image Off', component: ImageOff },
  { name: 'image-play', label: 'Image Play', component: ImagePlay },
  { name: 'image-plus', label: 'Image Plus', component: ImagePlus },
  { name: 'image-up', label: 'Image Up', component: ImageUp },
  { name: 'images', label: 'Images', component: Images },
  { name: 'inbox', label: 'Inbox', component: Inbox },
  { name: 'infinity', label: 'Infinity', component: Infinity },
  { name: 'info', label: 'Info', component: Info },
  { name: 'italic', label: 'Italic', component: Italic },
  { name: 'joystick', label: 'Joystick', component: Joystick },
  { name: 'kanban', label: 'Kanban', component: Kanban },
  { name: 'key', label: 'Key', component: Key },
  { name: 'key-round', label: 'Key Round', component: KeyRound },
  { name: 'key-square', label: 'Key Square', component: KeySquare },
  { name: 'keyboard', label: 'Keyboard', component: Keyboard },
  { name: 'lamp', label: 'Lamp', component: Lamp },
  { name: 'landmark', label: 'Landmark', component: Landmark },
  { name: 'languages', label: 'Languages', component: Languages },
  { name: 'laptop', label: 'Laptop', component: Laptop },
  { name: 'laugh', label: 'Laugh', component: Laugh },
  { name: 'layers', label: 'Layers', component: Layers },
  { name: 'layout-dashboard', label: 'Layout Dashboard', component: LayoutDashboard },
  { name: 'layout-grid', label: 'Layout Grid', component: LayoutGrid },
  { name: 'layout-list', label: 'Layout List', component: LayoutList },
  { name: 'layout-panel-left', label: 'Layout Panel Left', component: LayoutPanelLeft },
  { name: 'layout-panel-top', label: 'Layout Panel Top', component: LayoutPanelTop },
  { name: 'layout-template', label: 'Layout Template', component: LayoutTemplate },
  { name: 'leaf', label: 'Leaf', component: Leaf },
  { name: 'library', label: 'Library', component: Library },
  { name: 'library-big', label: 'Library Big', component: LibraryBig },
  { name: 'life-buoy', label: 'Life Buoy', component: LifeBuoy },
  { name: 'lightbulb', label: 'Lightbulb', component: Lightbulb },
  { name: 'line-chart', label: 'Line Chart', component: LineChart },
  { name: 'link', label: 'Link', component: Link },
  { name: 'link-2', label: 'Link 2', component: Link2 },
  { name: 'list', label: 'List', component: List },
  { name: 'list-checks', label: 'List Checks', component: ListChecks },
  { name: 'list-collapse', label: 'List Collapse', component: ListCollapse },
  { name: 'list-end', label: 'List End', component: ListEnd },
  { name: 'list-filter', label: 'List Filter', component: ListFilter },
  { name: 'list-minus', label: 'List Minus', component: ListMinus },
  { name: 'list-ordered', label: 'List Ordered', component: ListOrdered },
  { name: 'list-plus', label: 'List Plus', component: ListPlus },
  { name: 'list-restart', label: 'List Restart', component: ListRestart },
  { name: 'list-start', label: 'List Start', component: ListStart },
  { name: 'list-todo', label: 'List Todo', component: ListTodo },
  { name: 'list-tree', label: 'List Tree', component: ListTree },
  { name: 'list-x', label: 'List X', component: ListX },
  { name: 'loader-2', label: 'Loader 2', component: Loader2 },
  { name: 'locate', label: 'Locate', component: Locate },
  { name: 'locate-fixed', label: 'Locate Fixed', component: LocateFixed },
  { name: 'locate-off', label: 'Locate Off', component: LocateOff },
  { name: 'lock', label: 'Lock', component: Lock },
  { name: 'lock-keyhole', label: 'Lock Keyhole', component: LockKeyhole },
  { name: 'lock-open', label: 'Lock Open', component: LockOpen },
  { name: 'log-in', label: 'Log In', component: LogIn },
  { name: 'log-out', label: 'Log Out', component: LogOut },
  { name: 'lollipop', label: 'Lollipop', component: Lollipop },
  { name: 'magnet', label: 'Magnet', component: Magnet },
  { name: 'mail', label: 'Mail', component: Mail },
  { name: 'mail-check', label: 'Mail Check', component: MailCheck },
  { name: 'mail-minus', label: 'Mail Minus', component: MailMinus },
  { name: 'mail-open', label: 'Mail Open', component: MailOpen },
  { name: 'mail-plus', label: 'Mail Plus', component: MailPlus },
  { name: 'mail-question', label: 'Mail Question', component: MailQuestion },
  { name: 'mail-warning', label: 'Mail Warning', component: MailWarning },
  { name: 'mail-x', label: 'Mail X', component: MailX },
  { name: 'map', label: 'Map', component: Map },
  { name: 'map-pin', label: 'Map Pin', component: MapPin },
  { name: 'map-pin-off', label: 'Map Pin Off', component: MapPinOff },
  { name: 'map-pinned', label: 'Map Pinned', component: MapPinned },
  { name: 'maximize', label: 'Maximize', component: Maximize },
  { name: 'maximize-2', label: 'Maximize 2', component: Maximize2 },
  { name: 'medal', label: 'Medal', component: Medal },
  { name: 'megaphone', label: 'Megaphone', component: Megaphone },
  { name: 'meh', label: 'Meh', component: Meh },
  { name: 'menu', label: 'Menu', component: Menu },
  { name: 'merge', label: 'Merge', component: Merge },
  { name: 'message-circle', label: 'Message Circle', component: MessageCircle },
  { name: 'message-square', label: 'Message Square', component: MessageSquare },
  { name: 'messages-square', label: 'Messages Square', component: MessagesSquare },
  { name: 'mic', label: 'Mic', component: Mic },
  { name: 'mic-2', label: 'Mic 2', component: Mic2 },
  { name: 'mic-off', label: 'Mic Off', component: MicOff },
  { name: 'microscope', label: 'Microscope', component: Microscope },
  { name: 'microwave', label: 'Microwave', component: Microwave },
  { name: 'milestone', label: 'Milestone', component: Milestone },
  { name: 'milk', label: 'Milk', component: Milk },
  { name: 'minimize', label: 'Minimize', component: Minimize },
  { name: 'minimize-2', label: 'Minimize 2', component: Minimize2 },
  { name: 'minus', label: 'Minus', component: Minus },
  { name: 'monitor', label: 'Monitor', component: Monitor },
  { name: 'monitor-play', label: 'Monitor Play', component: MonitorPlay },
  { name: 'monitor-smartphone', label: 'Monitor Smartphone', component: MonitorSmartphone },
  { name: 'monitor-speaker', label: 'Monitor Speaker', component: MonitorSpeaker },
  { name: 'moon', label: 'Moon', component: Moon },
  { name: 'moon-star', label: 'Moon Star', component: MoonStar },
  { name: 'more-horizontal', label: 'More Horizontal', component: MoreHorizontal },
  { name: 'more-vertical', label: 'More Vertical', component: MoreVertical },
  { name: 'mountain', label: 'Mountain', component: Mountain },
  { name: 'mouse', label: 'Mouse', component: Mouse },
  { name: 'mouse-pointer', label: 'Mouse Pointer', component: MousePointer },
  { name: 'mouse-pointer-2', label: 'Mouse Pointer 2', component: MousePointer2 },
  { name: 'move', label: 'Move', component: Move },
  { name: 'move-3d', label: 'Move 3d', component: Move3d },
  { name: 'music', label: 'Music', component: Music },
  { name: 'music-2', label: 'Music 2', component: Music2 },
  { name: 'music-3', label: 'Music 3', component: Music3 },
  { name: 'music-4', label: 'Music 4', component: Music4 },
  { name: 'navigation', label: 'Navigation', component: Navigation },
  { name: 'navigation-off', label: 'Navigation Off', component: NavigationOff },
  { name: 'network', label: 'Network', component: Network },
  { name: 'newspaper', label: 'Newspaper', component: Newspaper },
  { name: 'nfc', label: 'Nfc', component: Nfc },
  { name: 'notebook', label: 'Notebook', component: Notebook },
  { name: 'notebook-pen', label: 'Notebook Pen', component: NotebookPen },
  { name: 'notebook-tabs', label: 'Notebook Tabs', component: NotebookTabs },
  { name: 'notebook-text', label: 'Notebook Text', component: NotebookText },
  { name: 'notepad-text', label: 'Notepad Text', component: NotepadText },
  { name: 'nut', label: 'Nut', component: Nut },
  { name: 'octagon', label: 'Octagon', component: Octagon },
  { name: 'octagon-alert', label: 'Octagon Alert', component: OctagonAlert },
  { name: 'orbit', label: 'Orbit', component: Orbit },
  { name: 'package', label: 'Package', component: Package },
  { name: 'package-2', label: 'Package 2', component: Package2 },
  { name: 'package-check', label: 'Package Check', component: PackageCheck },
  { name: 'package-minus', label: 'Package Minus', component: PackageMinus },
  { name: 'package-open', label: 'Package Open', component: PackageOpen },
  { name: 'package-plus', label: 'Package Plus', component: PackagePlus },
  { name: 'package-search', label: 'Package Search', component: PackageSearch },
  { name: 'package-x', label: 'Package X', component: PackageX },
  { name: 'paintbrush', label: 'Paintbrush', component: Paintbrush },
  { name: 'palette', label: 'Palette', component: Palette },
  { name: 'panel-bottom', label: 'Panel Bottom', component: PanelBottom },
  { name: 'panel-left', label: 'Panel Left', component: PanelLeft },
  { name: 'panel-left-close', label: 'Panel Left Close', component: PanelLeftClose },
  { name: 'panel-left-open', label: 'Panel Left Open', component: PanelLeftOpen },
  { name: 'panel-right', label: 'Panel Right', component: PanelRight },
  { name: 'panel-top', label: 'Panel Top', component: PanelTop },
  { name: 'paperclip', label: 'Paperclip', component: Paperclip },
  { name: 'parking-meter', label: 'Parking Meter', component: ParkingMeter },
  { name: 'pause', label: 'Pause', component: Pause },
  { name: 'paw-print', label: 'Paw Print', component: PawPrint },
  { name: 'pen-line', label: 'Pen Line', component: PenLine },
  { name: 'pen-tool', label: 'Pen Tool', component: PenTool },
  { name: 'pencil', label: 'Pencil', component: Pencil },
  { name: 'pencil-line', label: 'Pencil Line', component: PencilLine },
  { name: 'pencil-ruler', label: 'Pencil Ruler', component: PencilRuler },
  { name: 'pentagon', label: 'Pentagon', component: Pentagon },
  { name: 'percent', label: 'Percent', component: Percent },
  { name: 'phone', label: 'Phone', component: Phone },
  { name: 'phone-call', label: 'Phone Call', component: PhoneCall },
  { name: 'phone-forwarded', label: 'Phone Forwarded', component: PhoneForwarded },
  { name: 'phone-incoming', label: 'Phone Incoming', component: PhoneIncoming },
  { name: 'phone-missed', label: 'Phone Missed', component: PhoneMissed },
  { name: 'phone-off', label: 'Phone Off', component: PhoneOff },
  { name: 'phone-outgoing', label: 'Phone Outgoing', component: PhoneOutgoing },
  { name: 'pi', label: 'Pi', component: Pi },
  { name: 'pickaxe', label: 'Pickaxe', component: Pickaxe },
  { name: 'picture-in-picture', label: 'Picture In Picture', component: PictureInPicture },
  { name: 'picture-in-picture-2', label: 'Picture In Picture 2', component: PictureInPicture2 },
  { name: 'pie-chart', label: 'Pie Chart', component: PieChart },
  { name: 'piggy-bank', label: 'Piggy Bank', component: PiggyBank },
  { name: 'pilcrow', label: 'Pilcrow', component: Pilcrow },
  { name: 'pill', label: 'Pill', component: Pill },
  { name: 'pill-bottle', label: 'Pill Bottle', component: PillBottle },
  { name: 'pin', label: 'Pin', component: Pin },
  { name: 'pin-off', label: 'Pin Off', component: PinOff },
  { name: 'pizza', label: 'Pizza', component: Pizza },
  { name: 'plane', label: 'Plane', component: Plane },
  { name: 'plane-landing', label: 'Plane Landing', component: PlaneLanding },
  { name: 'plane-takeoff', label: 'Plane Takeoff', component: PlaneTakeoff },
  { name: 'play', label: 'Play', component: Play },
  { name: 'plug', label: 'Plug', component: Plug },
  { name: 'plug-zap', label: 'Plug Zap', component: PlugZap },
  { name: 'plus', label: 'Plus', component: Plus },
  { name: 'popcorn', label: 'Popcorn', component: Popcorn },
  { name: 'power', label: 'Power', component: Power },
  { name: 'presentation', label: 'Presentation', component: Presentation },
  { name: 'printer', label: 'Printer', component: Printer },
  { name: 'projector', label: 'Projector', component: Projector },
  { name: 'puzzle', label: 'Puzzle', component: Puzzle },
  { name: 'qr-code', label: 'Qr Code', component: QrCode },
  { name: 'quote', label: 'Quote', component: Quote },
  { name: 'rabbit', label: 'Rabbit', component: Rabbit },
  { name: 'radar', label: 'Radar', component: Radar },
  { name: 'radio', label: 'Radio', component: Radio },
  { name: 'radio-tower', label: 'Radio Tower', component: RadioTower },
  { name: 'rat', label: 'Rat', component: Rat },
  { name: 'ratio', label: 'Ratio', component: Ratio },
  { name: 'receipt', label: 'Receipt', component: Receipt },
  { name: 'receipt-cent', label: 'Receipt Cent', component: ReceiptCent },
  { name: 'receipt-text', label: 'Receipt Text', component: ReceiptText },
  { name: 'recycle', label: 'Recycle', component: Recycle },
  { name: 'redo', label: 'Redo', component: Redo },
  { name: 'refresh-ccw', label: 'Refresh Ccw', component: RefreshCcw },
  { name: 'refresh-cw', label: 'Refresh Cw', component: RefreshCw },
  { name: 'refresh-cw-off', label: 'Refresh Cw Off', component: RefreshCwOff },
  { name: 'refrigerator', label: 'Refrigerator', component: Refrigerator },
  { name: 'remove-formatting', label: 'Remove Formatting', component: RemoveFormatting },
  { name: 'reply', label: 'Reply', component: Reply },
  { name: 'reply-all', label: 'Reply All', component: ReplyAll },
  { name: 'rocket', label: 'Rocket', component: Rocket },
  { name: 'rocking-chair', label: 'Rocking Chair', component: RockingChair },
  { name: 'rotate-3d', label: 'Rotate 3d', component: Rotate3d },
  { name: 'rotate-ccw', label: 'Rotate Ccw', component: RotateCcw },
  { name: 'route', label: 'Route', component: Route },
  { name: 'route-off', label: 'Route Off', component: RouteOff },
  { name: 'router', label: 'Router', component: Router },
  { name: 'rows', label: 'Rows', component: Rows },
  { name: 'rows-2', label: 'Rows 2', component: Rows2 },
  { name: 'rows-3', label: 'Rows 3', component: Rows3 },
  { name: 'rows-4', label: 'Rows 4', component: Rows4 },
  { name: 'rss', label: 'Rss', component: Rss },
  { name: 'ruler', label: 'Ruler', component: Ruler },
  { name: 'sailboat', label: 'Sailboat', component: Sailboat },
  { name: 'salad', label: 'Salad', component: Salad },
  { name: 'sandwich', label: 'Sandwich', component: Sandwich },
  { name: 'satellite', label: 'Satellite', component: Satellite },
  { name: 'satellite-dish', label: 'Satellite Dish', component: SatelliteDish },
  { name: 'save', label: 'Save', component: Save },
  { name: 'scale', label: 'Scale', component: Scale },
  { name: 'scan', label: 'Scan', component: Scan },
  { name: 'scan-barcode', label: 'Scan Barcode', component: ScanBarcode },
  { name: 'scan-eye', label: 'Scan Eye', component: ScanEye },
  { name: 'scan-face', label: 'Scan Face', component: ScanFace },
  { name: 'scan-heart', label: 'Scan Heart', component: ScanHeart },
  { name: 'scan-line', label: 'Scan Line', component: ScanLine },
  { name: 'scan-search', label: 'Scan Search', component: ScanSearch },
  { name: 'scan-text', label: 'Scan Text', component: ScanText },
  { name: 'school', label: 'School', component: School },
  { name: 'scissors', label: 'Scissors', component: Scissors },
  { name: 'screen-share', label: 'Screen Share', component: ScreenShare },
  { name: 'screen-share-off', label: 'Screen Share Off', component: ScreenShareOff },
  { name: 'scroll', label: 'Scroll', component: Scroll },
  { name: 'scroll-text', label: 'Scroll Text', component: ScrollText },
  { name: 'search', label: 'Search', component: Search },
  { name: 'send', label: 'Send', component: Send },
  { name: 'send-horizontal', label: 'Send Horizontal', component: SendHorizontal },
  { name: 'server', label: 'Server', component: Server },
  { name: 'server-cog', label: 'Server Cog', component: ServerCog },
  { name: 'server-crash', label: 'Server Crash', component: ServerCrash },
  { name: 'server-off', label: 'Server Off', component: ServerOff },
  { name: 'settings', label: 'Settings', component: Settings },
  { name: 'shapes', label: 'Shapes', component: Shapes },
  { name: 'share', label: 'Share', component: Share },
  { name: 'share-2', label: 'Share 2', component: Share2 },
  { name: 'sheet', label: 'Sheet', component: Sheet },
  { name: 'shell', label: 'Shell', component: Shell },
  { name: 'shield', label: 'Shield', component: Shield },
  { name: 'shield-alert', label: 'Shield Alert', component: ShieldAlert },
  { name: 'shield-ban', label: 'Shield Ban', component: ShieldBan },
  { name: 'shield-check', label: 'Shield Check', component: ShieldCheck },
  { name: 'shield-half', label: 'Shield Half', component: ShieldHalf },
  { name: 'shield-question', label: 'Shield Question', component: ShieldQuestion },
  { name: 'shield-x', label: 'Shield X', component: ShieldX },
  { name: 'ship', label: 'Ship', component: Ship },
  { name: 'ship-wheel', label: 'Ship Wheel', component: ShipWheel },
  { name: 'shirt', label: 'Shirt', component: Shirt },
  { name: 'shopping-bag', label: 'Shopping Bag', component: ShoppingBag },
  { name: 'shopping-basket', label: 'Shopping Basket', component: ShoppingBasket },
  { name: 'shopping-cart', label: 'Shopping Cart', component: ShoppingCart },
  { name: 'shovel', label: 'Shovel', component: Shovel },
  { name: 'shower-head', label: 'Shower Head', component: ShowerHead },
  { name: 'shrink', label: 'Shrink', component: Shrink },
  { name: 'sidebar', label: 'Sidebar', component: Sidebar },
  { name: 'sigma', label: 'Sigma', component: Sigma },
  { name: 'signal', label: 'Signal', component: Signal },
  { name: 'signal-high', label: 'Signal High', component: SignalHigh },
  { name: 'signal-low', label: 'Signal Low', component: SignalLow },
  { name: 'signpost', label: 'Signpost', component: Signpost },
  { name: 'signpost-big', label: 'Signpost Big', component: SignpostBig },
  { name: 'siren', label: 'Siren', component: Siren },
  { name: 'skip-back', label: 'Skip Back', component: SkipBack },
  { name: 'skip-forward', label: 'Skip Forward', component: SkipForward },
  { name: 'sliders-horizontal', label: 'Sliders Horizontal', component: SlidersHorizontal },
  { name: 'smartphone', label: 'Smartphone', component: Smartphone },
  { name: 'smile', label: 'Smile', component: Smile },
  { name: 'snail', label: 'Snail', component: Snail },
  { name: 'snowflake', label: 'Snowflake', component: Snowflake },
  { name: 'sort-asc', label: 'Sort Asc', component: SortAsc },
  { name: 'sort-desc', label: 'Sort Desc', component: SortDesc },
  { name: 'soup', label: 'Soup', component: Soup },
  { name: 'spade', label: 'Spade', component: Spade },
  { name: 'sparkle', label: 'Sparkle', component: Sparkle },
  { name: 'sparkles', label: 'Sparkles', component: Sparkles },
  { name: 'speaker', label: 'Speaker', component: Speaker },
  { name: 'speech', label: 'Speech', component: Speech },
  { name: 'spell-check', label: 'Spell Check', component: SpellCheck },
  { name: 'split', label: 'Split', component: Split },
  { name: 'sprout', label: 'Sprout', component: Sprout },
  { name: 'square', label: 'Square', component: Square },
  { name: 'square-arrow-out-down-left', label: 'Square Arrow Out Down Left', component: SquareArrowOutDownLeft },
  { name: 'square-arrow-out-down-right', label: 'Square Arrow Out Down Right', component: SquareArrowOutDownRight },
  { name: 'square-arrow-out-up-left', label: 'Square Arrow Out Up Left', component: SquareArrowOutUpLeft },
  { name: 'square-arrow-out-up-right', label: 'Square Arrow Out Up Right', component: SquareArrowOutUpRight },
  { name: 'square-check', label: 'Square Check', component: SquareCheck },
  { name: 'square-kanban', label: 'Square Kanban', component: SquareKanban },
  { name: 'square-minus', label: 'Square Minus', component: SquareMinus },
  { name: 'square-pen', label: 'Square Pen', component: SquarePen },
  { name: 'square-plus', label: 'Square Plus', component: SquarePlus },
  { name: 'square-x', label: 'Square X', component: SquareX },
  { name: 'squirrel', label: 'Squirrel', component: Squirrel },
  { name: 'stamp', label: 'Stamp', component: Stamp },
  { name: 'star', label: 'Star', component: Star },
  { name: 'stars', label: 'Stars', component: Stars },
  { name: 'stethoscope', label: 'Stethoscope', component: Stethoscope },
  { name: 'sticky-note', label: 'Sticky Note', component: StickyNote },
  { name: 'store', label: 'Store', component: Store },
  { name: 'sun', label: 'Sun', component: Sun },
  { name: 'sunrise', label: 'Sunrise', component: Sunrise },
  { name: 'sunset', label: 'Sunset', component: Sunset },
  { name: 'swords', label: 'Swords', component: Swords },
  { name: 'syringe', label: 'Syringe', component: Syringe },
  { name: 'table', label: 'Table', component: Table },
  { name: 'table-2', label: 'Table 2', component: Table2 },
  { name: 'table-properties', label: 'Table Properties', component: TableProperties },
  { name: 'tablet', label: 'Tablet', component: Tablet },
  { name: 'tablet-smartphone', label: 'Tablet Smartphone', component: TabletSmartphone },
  { name: 'tag', label: 'Tag', component: Tag },
  { name: 'tags', label: 'Tags', component: Tags },
  { name: 'target', label: 'Target', component: Target },
  { name: 'telescope', label: 'Telescope', component: Telescope },
  { name: 'tent', label: 'Tent', component: Tent },
  { name: 'terminal', label: 'Terminal', component: Terminal },
  { name: 'test-tube', label: 'Test Tube', component: TestTube },
  { name: 'text', label: 'Text', component: Text },
  { name: 'text-cursor', label: 'Text Cursor', component: TextCursor },
  { name: 'text-search', label: 'Text Search', component: TextSearch },
  { name: 'thermometer', label: 'Thermometer', component: Thermometer },
  { name: 'thermometer-snowflake', label: 'Thermometer Snowflake', component: ThermometerSnowflake },
  { name: 'thermometer-sun', label: 'Thermometer Sun', component: ThermometerSun },
  { name: 'thumbs-down', label: 'Thumbs Down', component: ThumbsDown },
  { name: 'thumbs-up', label: 'Thumbs Up', component: ThumbsUp },
  { name: 'ticket', label: 'Ticket', component: Ticket },
  { name: 'ticket-check', label: 'Ticket Check', component: TicketCheck },
  { name: 'ticket-minus', label: 'Ticket Minus', component: TicketMinus },
  { name: 'ticket-percent', label: 'Ticket Percent', component: TicketPercent },
  { name: 'ticket-plus', label: 'Ticket Plus', component: TicketPlus },
  { name: 'ticket-x', label: 'Ticket X', component: TicketX },
  { name: 'timer', label: 'Timer', component: Timer },
  { name: 'timer-off', label: 'Timer Off', component: TimerOff },
  { name: 'timer-reset', label: 'Timer Reset', component: TimerReset },
  { name: 'toggle-left', label: 'Toggle Left', component: ToggleLeft },
  { name: 'toggle-right', label: 'Toggle Right', component: ToggleRight },
  { name: 'touchpad', label: 'Touchpad', component: Touchpad },
  { name: 'traffic-cone', label: 'Traffic Cone', component: TrafficCone },
  { name: 'train', label: 'Train', component: Train },
  { name: 'train-front', label: 'Train Front', component: TrainFront },
  { name: 'tram-front', label: 'Tram Front', component: TramFront },
  { name: 'trash', label: 'Trash', component: Trash },
  { name: 'tree-pine', label: 'Tree Pine', component: TreePine },
  { name: 'trees', label: 'Trees', component: Trees },
  { name: 'triangle', label: 'Triangle', component: Triangle },
  { name: 'triangle-alert', label: 'Triangle Alert', component: TriangleAlert },
  { name: 'trophy', label: 'Trophy', component: Trophy },
  { name: 'truck', label: 'Truck', component: Truck },
  { name: 'turtle', label: 'Turtle', component: Turtle },
  { name: 'tv', label: 'Tv', component: Tv },
  { name: 'type', label: 'Type', component: Type },
  { name: 'umbrella', label: 'Umbrella', component: Umbrella },
  { name: 'underline', label: 'Underline', component: Underline },
  { name: 'undo', label: 'Undo', component: Undo },
  { name: 'university', label: 'University', component: University },
  { name: 'unlink', label: 'Unlink', component: Unlink },
  { name: 'unlink-2', label: 'Unlink 2', component: Unlink2 },
  { name: 'unlock', label: 'Unlock', component: Unlock },
  { name: 'upload', label: 'Upload', component: Upload },
  { name: 'upload-cloud', label: 'Upload Cloud', component: UploadCloud },
  { name: 'usb', label: 'Usb', component: Usb },
  { name: 'user', label: 'User', component: User },
  { name: 'user-check', label: 'User Check', component: UserCheck },
  { name: 'user-cog', label: 'User Cog', component: UserCog },
  { name: 'user-minus', label: 'User Minus', component: UserMinus },
  { name: 'user-plus', label: 'User Plus', component: UserPlus },
  { name: 'user-round', label: 'User Round', component: UserRound },
  { name: 'user-round-check', label: 'User Round Check', component: UserRoundCheck },
  { name: 'user-round-cog', label: 'User Round Cog', component: UserRoundCog },
  { name: 'user-round-minus', label: 'User Round Minus', component: UserRoundMinus },
  { name: 'user-round-plus', label: 'User Round Plus', component: UserRoundPlus },
  { name: 'user-round-search', label: 'User Round Search', component: UserRoundSearch },
  { name: 'user-round-x', label: 'User Round X', component: UserRoundX },
  { name: 'user-search', label: 'User Search', component: UserSearch },
  { name: 'user-x', label: 'User X', component: UserX },
  { name: 'users', label: 'Users', component: Users },
  { name: 'users-2', label: 'Users 2', component: Users2 },
  { name: 'users-round', label: 'Users Round', component: UsersRound },
  { name: 'utensils', label: 'Utensils', component: Utensils },
  { name: 'utensils-crossed', label: 'Utensils Crossed', component: UtensilsCrossed },
  { name: 'variable', label: 'Variable', component: Variable },
  { name: 'verified', label: 'Verified', component: Verified },
  { name: 'video', label: 'Video', component: Video },
  { name: 'video-off', label: 'Video Off', component: VideoOff },
  { name: 'voicemail', label: 'Voicemail', component: Voicemail },
  { name: 'volume-2', label: 'Volume 2', component: Volume2 },
  { name: 'volume-x', label: 'Volume X', component: VolumeX },
  { name: 'wallet', label: 'Wallet', component: Wallet },
  { name: 'wand-2', label: 'Wand 2', component: Wand2 },
  { name: 'warehouse', label: 'Warehouse', component: Warehouse },
  { name: 'washing-machine', label: 'Washing Machine', component: WashingMachine },
  { name: 'watch', label: 'Watch', component: Watch },
  { name: 'waypoints', label: 'Waypoints', component: Waypoints },
  { name: 'webcam', label: 'Webcam', component: Webcam },
  { name: 'wheat', label: 'Wheat', component: Wheat },
  { name: 'whole-word', label: 'Whole Word', component: WholeWord },
  { name: 'wifi', label: 'Wifi', component: Wifi },
  { name: 'wind', label: 'Wind', component: Wind },
  { name: 'workflow', label: 'Workflow', component: Workflow },
  { name: 'worm', label: 'Worm', component: Worm },
  { name: 'wrench', label: 'Wrench', component: Wrench },
  { name: 'x', label: 'X', component: X },
  { name: 'x-circle', label: 'X Circle', component: XCircle },
  { name: 'zap', label: 'Zap', component: Zap },
  { name: 'zap-off', label: 'Zap Off', component: ZapOff },
] as const

export type IconographyName = (typeof iconography)[number]['name']

export const iconographyNames = iconography.map((item) => item.name)

export const iconographyComponents = Object.fromEntries(
  iconography.map((item) => [item.name, item.component]),
) as Record<IconographyName, VueComponent>

export const iconographySelectOptions = [
  { label: 'None', value: '' },
  ...iconography.map((item) => ({ label: item.label, value: item.name })),
]

export type ButtonIconName = IconographyName

export const buttonIconNames = iconographyNames
export const buttonIcons = iconographyComponents
